"""
Pydantic request/response models shared across routers.
Keeping these in one place is what lets Track A and Track B (and later
Track C/D) stay compatible without the agents building them needing to
coordinate directly.
"""
from typing import Literal, Optional
from pydantic import BaseModel, Field

Tone = Literal["simple", "technical", "connect"]
PaperStatus = Literal["uploaded", "parsing", "ready", "parse_failed", "empty_text"]


class UploadResponse(BaseModel):
    paper_id: str
    status: PaperStatus
    filename: str
    structure: dict
    message: Optional[str] = None
    reused_existing: bool = False


class SummarizeRequest(BaseModel):
    paper_id: str
    tone: Tone


class SummarizeResponse(BaseModel):
    paper_id: str
    tone: Tone
    content: str
    cached: bool = Field(
        description="True if this summary was already generated and served from cache, "
        "False if it was just generated by an OpenRouter call."
    )


class ErrorResponse(BaseModel):
    detail: str


# --- Track C: Q&A -----------------------------------------------------

class AskRequest(BaseModel):
    paper_id: str
    question: str


class AskResponse(BaseModel):
    paper_id: str
    answer: str
    used_sections: list[str] = Field(default_factory=list)


class ChatTurn(BaseModel):
    role: Literal["user", "assistant"]
    content: str


# --- Track D: Analysis --------------------------------------------------

class AnalyzeRequest(BaseModel):
    paper_id: str


class ChartPoint(BaseModel):
    label: str
    value: int


class Classification(BaseModel):
    paper_type: str
    complexity: str
    complexity_score: int


class AnalyzeResponse(BaseModel):
    paper_id: str
    section_lengths: list[ChartPoint]
    keywords: list[ChartPoint]
    classification: Optional[Classification] = None
    cached: bool = Field(
        description="True if served from the analysis cache, False if just computed."
    )
