"""
Pydantic request/response models shared across routers.
Keeping these in one place is what lets Track A and Track B (and later
Track C/D) stay compatible without the agents building them needing to
coordinate directly.
"""
from typing import Literal, Optional
from pydantic import BaseModel, Field

Tone = Literal["simple", "technical", "connect"]
PaperStatus = Literal["uploaded", "parsing", "ready", "parse_failed", "empty_text"]


class UploadResponse(BaseModel):
    paper_id: str
    status: PaperStatus
    filename: str
    structure: dict
    message: Optional[str] = None
    reused_existing: bool = False


class SummarizeRequest(BaseModel):
    paper_id: str
    tone: Tone


class SummarizeResponse(BaseModel):
    paper_id: str
    tone: Tone
    content: str
    cached: bool = Field(
        description="True if this summary was already generated and served from cache, "
        "False if it was just generated by an OpenRouter call."
    )


class ErrorResponse(BaseModel):
    detail: str


# --- Track C: Q&A -----------------------------------------------------

class AskRequest(BaseModel):
    paper_id: str
    question: str


class AskResponse(BaseModel):
    paper_id: str
    answer: str
    used_sections: list[str] = Field(default_factory=list)


class ChatTurn(BaseModel):
    role: Literal["user", "assistant"]
    content: str


# --- Track D: Analysis --------------------------------------------------

class AnalyzeRequest(BaseModel):
    paper_id: str


class ChartPoint(BaseModel):
    label: str
    value: int


class Classification(BaseModel):
    paper_type: str
    complexity: str
    complexity_score: int


class AnalyzeResponse(BaseModel):
    paper_id: str
    section_lengths: list[ChartPoint]
    keywords: list[ChartPoint]
    classification: Optional[Classification] = None
    cached: bool = Field(
        description="True if served from the analysis cache, False if just computed."
    )

# --- Track I: session aggregate -----------------------------------------

class PaperInfo(BaseModel):
    paper_id: str
    filename: str
    status: PaperStatus
    structure: dict


class SessionResponse(BaseModel):
    """
    Everything the frontend needs to fully restore a paper's state after
    a reload — one call instead of re-fetching upload/summarize/analyze/
    ask results piecemeal. Nothing here triggers new LLM generation; it
    only reads what's already cached in Supabase.
    """
    paper: PaperInfo
    summaries: dict[str, str] = Field(
        default_factory=dict, description="tone -> cached summary content, only tones already generated"
    )
    analysis: Optional[AnalyzeResponse] = None
    chat_history: list[ChatTurn] = Field(default_factory=list)

# --- Track J: figures (vision) -------------------------------------------

ImageType = Literal["chart", "diagram", "table", "code", "photo", "other"]


class Figure(BaseModel):
    id: str
    paper_id: str
    page_number: int
    image_type: Optional[ImageType] = None
    caption: Optional[str] = None
    width: int
    height: int


class FiguresResponse(BaseModel):
    paper_id: str
    figures: list[Figure]
    cached: bool = Field(
        description="True if every figure already had a caption; False if at least one was just captioned."
    )